version: "3"

services:
  svelte:
    build:
      context: ./web_client/
    networks:
      - app-network
  fastapi:
    build:
      context: ./server/
    depends_on:
      - database
    networks:
      - app-network
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - svelte
      - fastapi
    networks:
      - app-network
  database:
    image: postgres:latest
    networks:
      - app-network
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "123gr"
      POSTGRES_DB: "meowapp"

networks:
  app-network: